Added Frank Foster
wwdc/2020 pull request #107
Opened 2020-06-10 15:29 UTC by analogpotato

I just realized I made an error and didn't put anything in the Youtube section for my submission. I don't have a Youtube link so I may create another PR to fix my submission line.

2020-06-13 20:46 UTC, zmknox requested changes

2020-06-13 20:46 UTC, zmknox commented on README.md
> +|[Frank Foster](https://twitter.com/frankefoster)|[Github](https://github.com/analogpotato/WWDCSubmission)|AVFoundation, Vision, Visionkit|Submitted|
```suggestion
|[Frank Foster](https://twitter.com/frankefoster)|[Github](https://github.com/analogpotato/WWDCSubmission)||AVFoundation, Vision, VisionKit|Submitted|
```
This should fix your entry line

2020-06-14 07:20 UTC, analogpotato reviewed
made changes, thank you!

2020-06-16 01:21 UTC, zmknox approved these changes

2020-06-16 01:21 UTC, merged