add Giovanni Gorgone
wwdc/2020 pull request #250
Opened 2020-06-19 23:14 UTC by ggorgone

2020-06-21 19:57 UTC, zmknox requested changes

2020-06-21 19:57 UTC, zmknox commented on README.md
> +|[Giovanni Gorgone](linkedin.com/in/giovanni-gorgone)|[GitHub](https://github.com/ggorgone/WWDC2020_submission)||SwiftUI, AVFoundation|Accepted|
```suggestion
|[Giovanni Gorgone](https://linkedin.com/in/giovanni-gorgone)|[GitHub](https://github.com/ggorgone/WWDC2020_submission)||SwiftUI, AVFoundation|Accepted|
```
Making sure your link will be valid

2020-06-21 21:13 UTC, ggorgone commented on README.md
> +|[Giovanni Gorgone](linkedin.com/in/giovanni-gorgone)|[GitHub](https://github.com/ggorgone/WWDC2020_submission)||SwiftUI, AVFoundation|Accepted|
thank you!

2020-06-22 03:42 UTC, zmknox approved these changes

2020-06-22 03:42 UTC, merged