Update by added Joao Paulo Santos profile
wwdc/2020 pull request #265
Opened 2020-06-24 15:22 UTC by jppsantos

2020-06-28 19:18 UTC, zmknox requested changes

2020-06-28 19:18 UTC, zmknox commented on README.md
> +|[João Paulo Santos](https://www.linkedin.com/in/joao-ppsantos/)|[GitHub](https://github.com/jppsantos/WWDC_EmpathyChallenge)|[YouTube](https://www.youtube.com/watch?v=8C5BjjiLf5Y&t=6s)|SpriteKit, Ga
```suggestion
|[João Paulo Santos](https://www.linkedin.com/in/joao-ppsantos/)|[GitHub](https://github.com/jppsantos/WWDC_EmpathyChallenge)|[YouTube](https://www.youtube.com/watch?v=8C5BjjiLf5Y)|SpriteKit, GameplayKit|Accepted|
```
Removed timestamp which had your video starting at 6 seconds in

2020-07-03 14:23 UTC, jppsantos commented
Hi, timestamp removed. https://github.com/wwdc/2020/pull/265/commits/1cf0579e58ee3b6303a06ed5acff66718b37c367

2020-07-05 20:44 UTC, zmknox approved these changes

2020-07-05 20:44 UTC, merged