added me :D
wwdc/2020 pull request #92
Opened 2020-05-23 12:43 UTC by xReee

2020-05-25 23:45 UTC, zmknox requested changes

2020-05-25 23:45 UTC, zmknox commented on README.md
> +|[Renata Faria](http://renatafariagomes.wordpress.com/)|[GitHub](https://github.com/xReee/WWDC2020)|[Youtube](https://www.youtube.com/watch?v=fZ3ilbJx5_8)|UIKit, GameplayKit, AVKit |Submitted|
Please lace your entry in alphabetical order by first name. Yours is close, needs to be moved up a few lines.

2020-05-26 16:42 UTC, xReee reviewed
done :)

2020-05-28 02:16 UTC, zmknox approved these changes

2020-05-28 02:16 UTC, merged